version: "3.9"
services:
  web:
    image: urnau/php82-app-2023
    container_name: web
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      # dockerfile: ./docker/Dockerfile.light
      args:
        PHP_VERSION: '8.2.4-fpm-bullseye'
    # volumes:
    #   - ./app:/var/www/app
    ports:
      - "80:80" #http
      - "443:443" #https
      
  web-light:
    image: urnau/php82-app-2023:light
    container_name: web-light
    build:
      context: .
      dockerfile: ./docker/Dockerfile.light
      args:
        PHP_VERSION: '8.2.4-fpm-bullseye'
    volumes:
      - ./app:/var/www/app
    ports:
      - "80:80" #http
      - "443:443" #https

  web-octane:
    image: urnau/php82-app-2023:octane
    container_name: web-octane
    build:
      context: .
      dockerfile: ./docker/Dockerfile.octane
      args:
        PHP_VERSION: '8.2.4-bullseye'
    ports:
      - "80:80" #http
      - "443:443" #https

  web-horizon:
    image: urnau/php82-app-2023:horizon
    container_name: web-horizon
    build:
      context: .
      dockerfile: ./docker/Dockerfile.octane
      args:
        PHP_VERSION: '8.2.4-bullseye'
    ports:
      - "80:80" #http
      - "443:443" #https

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 200M
        reservations:
          cpus: "0.1"
          memory: 20M
      restart_policy:
        condition: on-failure